# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'nearbie' do
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'
  pod 'Firebase/Core'
  pod 'PhotoEditorSDK'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

end